### ISSUE TITLE
meaningful error handling

### ISSUE THREAD

**Issue by gotjoshua** [MoralisWeb3/issue-tracker#81]
we never get a reference to one of our line numbers.

not in these situations (errors on deploy):
``` 
2021-06-15T14:12:53.141Z - SyntaxError: Invalid or unexpected token
    at customUserPlugin (/moralis-server/cloud/main.js:8:21)
    at /moralis-server/lib/cloud-code/plugins/index.js:62:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.initialize (/moralis-server/lib/cloud-code/plugins/index.js:51:3)

2021-06-15T14:12:53.140Z - CLOUD FUNCTION ERROR PLEASE CHECK YOUR CLOUD FUNCTION CODE
```

nor in runtime errors eg:
```
2021-06-15T14:28:43.585Z - Error: [object Object]
    at Object.resolveError (/moralis-server/lib/triggers.js:631:17)
    at error (/moralis-server/lib/Routers/FunctionsRouter.js:107:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

we need a little help to "CHECK OUR CLOUD FUNCTION CODE"...
and to identify these errors more accurately.

**Comment by gerardo15** [comment]
The new watch cloud folder command from the cli provides a more detailed syntax error check

https://docs.moralis.io/moralis-server/tools/moralis-admin-cli#watch-cloud-folder
